=== hmrc/api-platform-test-user/resources/public/api/conf/1.0/schemas/create-individual-response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Create Individual Response",
  "type": "object",
  "properties": {
    "userId": {
      "type": "string",
      "description": "Government Gateway ID"
    },
    "password": {
      "type": "string",
      "description": "Government Gateway password"
    },
    "individualDetails": {
      "type": "object",
      "properties": {
        "firstName": {
          "type": "string",
          "description": "Individual's first name"
        },
        "lastName": {
          "type": "string",
          "description": "Individual's last name"
        },
        "dateOfBirth": {
          "type": "string",
          "format": "date",
          "description": "Individual's date of birth"
        },
        "address": {
          "type": "object",
          "properties": {
            "line1": {
              "type": "string",
              "description": "Individual's first line of address"
            },
            "line2": {
              "type": "string",
              "description": "Individual's second line of address"
            },
            "postcode": {
              "type": "string",
              "description": "Individual's postcode"
            }
          },
          "required": [
            "line1",
            "line2",
            "postcode"
          ]
        }
      },
      "required": [
        "firstName",
        "lastName",
        "dateOfBirth",
        "address"
      ]
    },
    "saUtr": {
      "type": "string",
      "description": "Self Assessment UTR"
    },
    "nino": {
      "type": "string",
      "description": "National Insurance number"
    },
    "mtdItId": {
      "type": "string",
      "description": "Making Tax Digital Income Tax ID"
    }
  },
  "required": [
    "userId",
    "password",
    "individualDetails"
  ]
}

=== hmrc/api-platform-test-user/resources/public/api/conf/1.0/examples/create-individual-response.json
{
  "userId":"945350439195",
  "password":"bLohysg8utsa",
  "individualDetails": {
    "firstName": "Ida",
    "lastName": "Newton",
    "dateOfBirth": "1960-06-01",
    "address": {
      "line1": "45 Springfield Rise",
      "line2": "Glasgow",
      "postcode": "TS1 1PA"
    }
  },
  "saUtr":"1000057161",
  "nino":"PE938808A",
  "mtdItId":"XJIT00000328268"
}
